common: &common
  adapter: postgresql
  username: jonahhalter
  password: 
  min_messages: warning

development:
  <<: *common
  database: service_development
  host: localhost

test:
  <<: *common
  database: service_development
  host: localhost

production:
  <<: *common
  database: service_production

